name: Dev CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install backend dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r backend/.venv/requirements.txt

      - name: Run backend health check
        run: |
          source .venv/bin/activate
          cd backend/.venv
          cp ../config.yaml .
          python app.py &
          sleep 5
          curl http://localhost:5000/api/healthcheck || exit 1
